Implement Google two step authentication.
gmail-manager-community/gmail-manager-community pull request #53
Opened 2017-05-07 09:52 UTC by m-soltys

2017-05-07 10:09 UTC, m-soltys commented
I think I also need to fix logging by clicking on the account name on the toolbar as it's not working with this two step authentication.

2017-05-07 10:59 UTC, ath0mas commented
Seen existing issue #45 for 1-click auto connect?

2017-05-07 12:39 UTC, m-soltys commented
Haven't sen that issue. Will fix that #45 issue in this PR.

2017-05-15 20:27 UTC, ath0mas requested changes
Please squash last commit with interactive rebase

2017-05-15 20:50 UTC, m-soltys commented
@ath0mas Done.

2017-05-15 20:59 UTC, ath0mas submitted a review, later dismissed

2017-05-15 21:06 UTC, ath0mas commented
Supposed to work seamlessly for accounts without 2-step auth?

2017-05-15 21:13 UTC, m-soltys commented
It's not working for the accounts without 2-step auth. I think that all accounts have it enabled so no need for supporting single step log in.

2017-05-15 21:20 UTC, ath0mas commented
I added current snapshot version to Firefox Dev Edition and tested with 1-step auth account:
- authentication is ok, and unread counts are back to normal 👍 

but one-click auto connect from toolbar or from mail snippet fails as before (I end up on https://support.google.com/accounts/answer/61416 or on Signin page)

2017-05-15 21:50 UTC, ath0mas commented
+ what type of 2-step verification to configure? compatible with sms, invite, ..., trusted devices, ..., with app password?

2017-05-16 18:03 UTC, m-soltys commented
I misled you probably. By the 2-step auth I mean two steps login into Google account. Not the real two factor authentication.

I don't have a much time lately but I will try to look at non working one-click login as soon as possible. For me and couple other persons it's working just fine.

2017-05-16 22:13 UTC, ath0mas commented
Indeed I misunderstood ;)
really great to have worked on this 2-step auth already!

(existing issues for 2-step _verification_ are #24 and #25)

2017-05-16 22:20 UTC, ath0mas commented
I'm thinking about releasing fix for auth _quickly_ - need to review PR corresponding code before though
and _later_, with more test, 1-click autoconnect and click on snippet (as not working either for me with your xpi shared on google drive in #51)

splitting commits to different PRs ?
What do you think is better?

2017-05-18 18:12 UTC, bacon-cheeseburger commented
I am currently testing "gmail_manager_community-0.7.5-SNAPSHOT-fx+sm.xpi" and can report that 1-click autoconnect/autologin is not working. Whenever I click on an account, I get taken to a page to enter the password for that account. Also, once I do log into an account, the new email count is always 0.

My experience is that this version of gmc isn't working at all unfortunately.

2017-05-18 18:27 UTC, internero commented
I am using the same version, gmail_manager_community-0.7.5-SNAPSHOT-fx+sm.xpi,
and have 7 accounts: 2 @gmail.com and 5 gapps.

Since I installed this version only one account have error exactly as you
mentioned: cannot login, 0 messages, 0 bytes used and when I click the new
page opens asking for a password.

The strange thing: all other 6 accounts are working very well, with
auto-login, message counts, refresh, 1-click login... all fine!

If I can make some tests, grab some logs, and help to test, give me some
directons on what I can do.

... and thanks for the fix! Its not 100%, but it IS a improvement to keep
plugin working after Google's changes.


internero



internero@gmail.com

On Thu, May 18, 2017 at 3:12 PM, bacon-cheeseburger <
notifications@github.com> wrote:

> I am currently testing "gmail_manager_community-0.7.5-SNAPSHOT-fx+sm.xpi"
> and can report that 1-click autoconnect/autologin is not working. Whenever
> I click on an account, I get taken to a page to enter the password for that
> account. Also, once I do log into an account, the new email count is always
> 0.
>
> My experience is that this version of gmc isn't working at all
> unfortunately.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gmail-manager-community/gmail-manager-community/pull/53#issuecomment-302496133>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAhyaV8YgCDQkYrj9bIYLzUb57q0vUIIks5r7IocgaJpZM4NTFZs>
> .
>

2017-05-18 18:37 UTC, m-soltys commented
Guys, I'm quite busy this week. Will look at all these issues at the end of this week or beginning of next week. 

I have 4 accounts and all of them are working just fine. Maybe you have some ideas or observations why it's working for some of your account and for others not. 

It would be appreciated and help me a lot if someone could create and share with me a test account that isn't working as I don't have non working account that I can debug and see where the problem is.

2017-05-22 23:05 UTC, ath0mas requested changes

2017-05-22 23:05 UTC, ath0mas commented on components/gmLogger.js
> +  this._debug = false;
Keep _debug previous value here or use commented block instead?

2017-05-22 23:05 UTC, ath0mas commented on chrome/content/utils/accounts.js
> +      var message = account.getMessage(account.password, aMessageId);
null param is same, as processed as `(aPassword || this.password)`
so, I would not change it

2017-05-22 23:05 UTC, ath0mas commented on chrome/content/utils/accounts.js
> +      var folder = account.getFolder(account.password, aFolderId);
do not change param here too

2017-05-22 23:05 UTC, ath0mas commented on chrome/content/alert/alert.js
> +    document.getElementById("gmanager-alert-description").value = gmanager_Utils.toUnicode(snippet.msg);
👍 but same change should be done on line 164 too

2017-05-22 23:05 UTC, ath0mas commented on components/gmConnection.js
> +    this._data = "";
why need to clear data?

2017-05-22 23:05 UTC, ath0mas commented on components/gmServiceGmail.js
> +    postUrl = this._extractActionUrlFromFormData(data);
duplicated lines 127-128 / 123-124?

2017-05-22 23:05 UTC, ath0mas commented on components/gmServiceGmail.js
> +    var data = connection.data;
really need to extract this `data` var or should be used directly with `connection.data` like on line 135?

2017-05-22 23:05 UTC, ath0mas commented on components/gmServiceGmail.js
> +      var cookieExpirationTime = !cookie.expires
I would not define new variable here but only change `cookie.expires` value as you do, to use it inside _cookieManager.add as before

2017-05-23 18:59 UTC, m-soltys commented on components/gmLogger.js
> +  this._debug = false;
Will use commented block instead, there is no need to have log turned on in released instances.

2017-05-23 19:06 UTC, m-soltys commented on components/gmConnection.js
> +    this._data = "";
As you can see in lines 69-71 there is appending the stream data to the _data variable. If you're using the send function on the same instance of gmConnection twice then data from the second request is appended to the data from the first request which is bad.

2017-05-23 19:12 UTC, m-soltys commented on components/gmServiceGmail.js
> +    postUrl = this._extractActionUrlFromFormData(data);
Did you miss the `connection.send` between duplication? The second part of code is working on the different response.  

The flow:
1. Get the login page from server - line 121
2. Parse the response and get required data - lines 123-124
3. Post request to the server with account name (1st step login) - line 125
4. Parse the response and get required data - 127-128

2017-05-23 19:14 UTC, m-soltys commented on chrome/content/utils/accounts.js
> +      var message = account.getMessage(account.password, aMessageId);
Don't get it. Could you explain? 

I need to pass the password to the `_getServiceURI` funciton as this._password was null for me.

2017-05-23 19:15 UTC, m-soltys commented on chrome/content/utils/accounts.js
> +      var folder = account.getFolder(account.password, aFolderId);
As explained.

2017-05-23 19:15 UTC, m-soltys commented on chrome/content/alert/alert.js
> +    document.getElementById("gmanager-alert-description").value = gmanager_Utils.toUnicode(snippet.msg);
Done.

2017-05-23 19:31 UTC, m-soltys commented on components/gmServiceGmail.js
> +      var cookieExpirationTime = !cookie.expires
My bad, missed that I'm changing `cookie.expires`. Will fix to use only the new variable. 

Shouldn't change function's argument.

2017-05-23 22:18 UTC, ath0mas commented on chrome/content/utils/accounts.js
> +      var message = account.getMessage(account.password, aMessageId);
Here it is `getMessage` from gmAccount not gmServiceGmail

2017-05-23 22:18 UTC, ath0mas commented on chrome/content/utils/accounts.js
> +      var folder = account.getFolder(account.password, aFolderId);
same 😋 
and see lines 102-104 with similar structure `account.getCompose(null, aHref)` (all 3 called with `null`)

2017-05-23 22:31 UTC, ath0mas commented on components/gmServiceGmail.js
> +    postUrl = this._extractActionUrlFromFormData(data);
fine, I did not see getter for `_data` behind `connection.data`

2017-05-23 22:31 UTC, ath0mas commented on components/gmConnection.js
> +    this._data = "";
fine

2017-05-23 22:34 UTC, ath0mas commented on components/gmServiceGmail.js
> +      var cookieExpirationTime = !cookie.expires
ok

2017-05-23 22:34 UTC, ath0mas commented on components/gmLogger.js
> +  this._debug = false;
can remove line 21?

2017-05-23 23:03 UTC, ath0mas requested changes

2017-05-23 23:03 UTC, ath0mas commented on components/gmLogger.js
> +  this._debug = false;
can remove line 21?

2017-05-25 17:39 UTC, m-soltys commented on chrome/content/utils/accounts.js
> +      var message = account.getMessage(account.password, aMessageId);
Ahhh I see it now, you're right.

2017-05-25 17:44 UTC, m-soltys commented on components/gmServiceGmail.js
> +      var cookieExpirationTime = !cookie.expires
I will never get used to JS :)

2017-05-25 17:47 UTC, m-soltys commented on components/gmLogger.js
> +  this._debug = false;
Done.

2017-05-26 00:46 UTC, ath0mas approved these changes

2017-05-26 00:48 UTC, merged